const MODULE_NAME = 'questions';

export const SAVE_NEW_QUESTION = `${MODULE_NAME}/SAVE_NEW_QUESTION`;
export const SET_QUESTIONS = `${MODULE_NAME}/SET_QUESTIONS`;
export const UPDATE_NEW_QUESTION_TEXT = `${MODULE_NAME}/UPDATE_NEW_QUESTION_TEXT`;
